name: Build Azure Function App .NET

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'your-app-name'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'DemoFunctionNet6'       # set this to the path to your function app project, defaults to the repository root
  CONFIGURATION: 'Release'

jobs:
  build-and-deploy:
    strategy:
      matrix:
        include:
          - DOTNET_VERSION: 8.0.x
            directory: net8
          - DOTNET_VERSION: 9.0.x
            directory: net9

    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    # If you want to use Azure RBAC instead of Publish Profile, then uncomment the task below
    # - name: 'Login via Azure CLI'
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }} # set up AZURE_RBAC_CREDENTIALS secrets in your repository

    - name: Setup DotNet ${{ matrix.DOTNET_VERSION}} Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.DOTNET_VERSION}}

    - name: 'Build .NET'
      working-directory: ${{ matrix.directory }}
      run: |
        dotnet publish Func --output $RUNNER_TEMP/output

        ls -al $RUNNER_TEMP/output

#    - name: 'Run Azure Functions Action'
#      uses: Azure/functions-action@v1
#      id: fa
#      with:
#        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
#        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
#        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # Remove publish-profile to use Azure RBAC
