name: Take down

on:
  schedule:
    - cron: "0 9 * * *" # 9am UTC
  workflow_dispatch:

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: "Login via Azure CLI"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep
        uses: azure/bicep-deploy@v2
        with:
          type: deploymentStack
          operation: delete
          name: Development
          location: australiaeast
          scope: resourceGroup
          resource-group-name: rg-funcs-logging-australiaeast
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          template-file: ./infra/main.bicep
          action-on-unmanage-resources: delete
          deny-settings-mode: none
